project:
  type: website
  output-dir: docs

website:
  title: "Michael Mullarkey's Blog"
  navbar:
    right:
      - icon: globe2
        href: https://mcmullarkey.github.io/ 
      - icon: github
        href: https://github.com/mcmullarkey
      - icon: linkedin
        href: https://www.linkedin.com/in/mcmullarkey/
      - icon: twitter
        href: https://twitter.com/mcmullarkey
      - icon: twitch
        href: https://www.twitch.tv/mcmullarkey
format:
  html:
    theme: cyborg
    css: styles.css

editor: visual

